baseURL = "https://selleo.com/devpath/"
languageCode = "en-us"
title = "Selleo DevPath Framework"
theme = "selleo"
canonifyURLs = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
